#!/usr/bin/python3
import io
import datetime

try:
  from setuptools import setup
except ImportError:
  from distutils.core import setup

from distutils.util import convert_path

def get_name():
  with io.open('Makefile') as f:
    for line in f:
      if line.startswith('PACKAGE'):
        (key,val) = line.split("=")
        print(val.strip())
        return(val.strip())

def get_version():
  with io.open('Makefile') as f:
    for line in f:
      if line.startswith('VERSION'):
        (key,val) = line.split("=")
        return(val.strip())

def set_version():
  vpath = convert_path(get_name()+'/_version.py')
  f = open(vpath, "w")
  f.write("#\n")
  f.write("# File generated by setup.py (%s)\n" % datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"))
  f.write("# Don't change or track this file in version control\n")
  f.write("version = '"+get_version()+"'\n")
  f.close()

with io.open('README.md') as readme:
  setup(
    void=set_version(),
    name=get_name(),
    packages=[get_name()],
    version=get_version(),
    description='AWI helper classes',
    long_description=readme.read(),
    install_requires=['wheel', 'pycryptodome'],
    author='Jeffrey Fulmer',
    author_email='jdfulmer@armstrongceilings.com',
    maintainer='Jeffrey Fulmer',
    maintainer_email='jdfulmer@armstrongceilings.com',
    url='https://git.armstrongceilings.com',
    download_url="https://git.armstrongceilings.com/scm/infra/%s.git" % get_name(),
    keywords=['password', 'AES'],
    platforms='any',
    classifiers=[
      'Environment :: Web Environment',
      'Intended Audience :: Developers',
      'Operating System :: OS Independent',
      'Programming Language :: Python',
      'Topic :: Password :: Encryption :: Dynamic Content',
      'Topic :: Software Development :: Libraries :: Python Modules'
    ],
    license='MIT',
  )
